### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by xgdgsc** [ericqu/LinearRegressionKit.jl#16]
Install this would downgrade a lot of packages. Are fixed versions in compat necessary?

**Comment by ericqu** [comment]
Well, that the versions I tested against.
But it could also be the result of my limited knowledge on how to specify the versions in the file. I got some errors messages from the package registry, that at the time push me into these fixed versions numbers.
This being said,  I could have look into it and check that the test passes with other versions as well. 
Could you share which packages are particularly problematic from your perspective?

**Comment by ericqu** [comment]
I made some changes that you can test by using the version associate with this issue.
In the Julia package manager you can use the following command to add this version:

`add https://github.com/ericqu/LinearRegressionKit.jl#16-update-deps`

let me know if this solve your problem or not.

**Comment by ericqu** [comment]
This should be fixed in version 0.7.11, which will become the default soon.
